
services:

  rcloneGUI:
    image: rclone/rclone
    container_name: rcloneGUI
    restart: always
    command: rcd --rc-web-gui --rc-addr :5572 --rc-no-auth
    ports:
      - "5572:5572"
    volumes:
      - ./rclone/:/config/rclone
      - ./rclone/:/logs
    environment:
      - PHP_TZ=Europe/London
      - PUID=1001
      - PGID=1001
    networks:
      - rclone-net

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
    container_name: oauth2-proxy
    restart: always
    ports:
      - "4180:4180"
    command:
      - --provider=oidc
      - --oidc-issuer-url=${IAM_AUTHORITY_URL}
      - --client-id=${IAM_CLIENT_ID}
      - --client-secret=${IAM_CLIENT_SECRET}
#      - --cookie-secret=3XtVEyXs0D1MB42Mu5xZTt90F8hUQmavVG7SCYiyqkI
      - --cookie-secret=${AUTH_SECRET}
      - --redirect-url=https://s3webui.cygno.cloud.infn.it/oauth2/callback
      - --http-address=0.0.0.0:4180
      - --email-domain=*
      - --upstream=http://rcloneGUI:5572/
      - --cookie-secure=true
    networks:
      - rclone-net


  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - rcloneGUI
      - oauth2-proxy
    networks:
      - rclone-net

networks:
  rclone-net:
    name: rclone-net
