


services:
#  rcloneGUI:
#    image: rclone/rclone
#    container_name: rcloneGUI
#    restart: always
#    command: rcd --rc-web-gui --rc-addr :5572 --rc-no-auth --rc-serve
#    ports:
#      - "5572:5572"
#    volumes:
#      - ./rclone/:/config/rclone
#      - ./rclone/:/logs
#      - /tmp/:/tmp/
#    environment:
#      - PHP_TZ=Europe/London
#      - PUID=1001
#      - PGID=1001
#    networks:
#      - rclone-net

  rcloneGUI:
    image: rclone/rclone
    container_name: rcloneGUI
#    restart: always
    environment:
      - PHP_TZ=Europe/London
      - PUID=1001
      - PGID=1001
      - BA_ACCESS_KEY_ID=${BA_ACCESS_KEY_ID}
      - BA_SECRET_ACCESS_KEY=${BA_SECRET_ACCESS_KEY}
      - S3_REGION=${S3_REGION}
    ports:
      - "5572:5572"
    volumes:
      - ${PWD}/rclone/:/logs
      - /tmp/:/tmp/
      - ${PWD}/rclone/rclone_entrypoint.sh:/config/rclone/rclone_entrypoint.sh
    networks:
      - rclone-net
    entrypoint: ["/bin/sh", "/config/rclone/rclone_entrypoint.sh"]
#    command: ["rcd", "--config", "/config/rclone/rclone.conf", "--rc-web-gui", "--rc-addr", ":5572", "--rc-no-auth", "--rc-serve"]



  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
    container_name: oauth2-proxy
    restart: always
    ports:
      - "4180:4180"
    command:
      - --provider=oidc
      - --oidc-issuer-url=${IAM_AUTHORITY_URL}
      - --client-id=${IAM_CLIENT_ID}
      - --client-secret=${IAM_CLIENT_SECRET}
      - --cookie-secret=${AUTH_SECRET}
      - --redirect-url=https://s3webui.cygno.cloud.infn.it/oauth2/callback
      - --http-address=0.0.0.0:4180
      - --email-domain=*
      - --upstream=http://rcloneGUI:5572/
      - --cookie-secure=true
    networks:
      - rclone-net

  tokener:
    image: gmazzitelli/tokener:v0.1
    container_name: tokener
    environment:
      REFRESH_TOKEN: ${IAM_REFRESH_TOKEN}
      IAM_CLIENT_SECRET: ${IAM_CLIENT_SECRET}
      IAM_CLIENT_ID: ${IAM_CLIENT_ID}
      IAM_TOKEN_ENDPOINT: ${IAM_TOKEN_ENDPOINT}
      SCOPES: "${IAM_SCOPE}"
    volumes:
      - /tmp/:/tmp/

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - tokener
      - rcloneGUI
      - oauth2-proxy
    networks:
      - rclone-net

networks:
  rclone-net:
    name: rclone-net
