services:

  rgw:
    image: baltig.infn.it:4567/infn-cloud/webapp-rgw
    container_name: rgw
    ports:
      - "8080:80"
    environment:
      - AUTH_URL=${AUTH_URL}
      - AUTH_SECRET=${AUTH_SECRET}
      - IAM_AUTHORITY_URL=${IAM_AUTHORITY_URL}
      - IAM_CLIENT_ID=${IAM_CLIENT_ID}
      - IAM_CLIENT_SECRET=${IAM_CLIENT_SECRET}
      - IAM_AUDIENCE=${IAM_AUDIENCE}
      - IAM_SCOPE=${IAM_SCOPE}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_REGION=${S3_REGION}
      - S3_ROLE_ARN=${S3_ROLE_ARN}
      - S3_ROLE_DURATION_SECONDS=${S3_ROLE_DURATION_SECONDS}

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - rgw
