services:

  rcloneGUI:
    image: rclone/rclone
    container_name: rcloneGUI
    restart: always
    command: rcd --rc-web-gui --rc-addr :5572 --rc-baseurl rclone --rc-htpasswd 
    ports:
      - "5572:5572"
    volumes:
      - ../editor/config/rclone/:/config/rclone
      - ../editor/config/rclone/:/logs
    environment:
      - PHP_TZ=Europe/London
      - PUID=1001
      - PGID=1001

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - rcloneGU
