version: '3'

services:

  grafana:
    image: grafana/grafana:9.5.7
    container_name: grafana
    user: "0"
    ports:
      - 3000:3000
    volumes:
      - dbdata:/var/lib/grafana

    environment:
      GF_INSTALL_PLUGINS: percona-percona-app,michaeldmoore-scatter-panel,natel-plotly-panel,ae3e-plotly-panel,volkovlabs-image-panel,simpod-json-datasource,marcusolsson-json-datasource

      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "pluto"
      GF_SECURITY_ALLOW_EMBEDDING: 1 

volumes:
   dbdata:
