version: '3'

services:

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: cygno_db
      MYSQL_USER: cygno_producer
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      GF_INSTALL_PLUGINS: percona-percona-app,michaeldmoore-scatter-panel,natel-plotly-panel,ae3e-plotly-panel
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      
  noip:
    image: uping/no-ip
    container_name: noip
    restart: unless-stopped
    environment:
      - USERNAME="cygno.daq.allert@gmail.com"
      - PASSWORD=${NO-IP_PASSWORD}
      - DOMAINS=${NO-IP_DOMAIN}
      - INTERVAL=1h
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/noip:/config

volumes:
  dbdata:

