version: '3'
services:

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 9754f510c12f8f1005cdb16dc51834c4
      MYSQL_DATABASE: cygno_db
      MYSQL_USER: cygno_producer
      MYSQL_PASSWORD: e3b46beda9650197978b7b7e80464f73

  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    environment:
      GF_INSTALL_PLUGINS: percona-percona-app
