version: '3'

services:

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: cygno_db
      MYSQL_USER: cygno_producer
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

  grafana:
    image: grafana/grafana
    
    [auth.generic_oauth]
    enabled = true
    allow_sign_up = true
    team_ids =
    allowed_organizations =
    name = IAM
    client_id = ******
    client_secret = *****
    scopes = openid profile email
    auth_url = https://iam.cloud.infn.it/authorize
    token_url = https://iam.cloud.infn.it/token
    api_url = https://iam.cloud.infn.it/userinfo
    cookie_secure=true
    role_attribute_path = contains(groups[*], cygno) && 'Editor'
    role_attribute_strict = true
    
    [server]
    ports:
      - 3000:3000
    environment:
      GF_INSTALL_PLUGINS: percona-percona-app,michaeldmoore-scatter-panel,natel-plotly-panel,ae3e-plotly-panel
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}

volumes:
  dbdata:

