# version: '3'
# https://hub.docker.com/_/mariadb
# docker compose con aggiunta del profiles: ["grafana"]  per SQL LNF e MANGO.
services:

  db:
    image: mariadb:10.5.15
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: cygno_db
      MYSQL_USER: cygno_producer
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#
# con networ_mode il reindirizzamento delle porte non funziona
#    ports: 
#      - "3307:3306"

    volumes:
      - ${PWD}/50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf
      - mariadb:/var/lib/mysql

    network_mode: host
#
# profiles: ["grafana"] per MANGO
#
  mango_db:
    image: mariadb:10.5.15
    container_name: mango_db
    profiles: ["grafana"]
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: mango_db
      MYSQL_USER: cygno_producer
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#
# con networ_mode il reindirizzamento delle porte non funziona
#    ports: 
#      - "3307:3306"
#
    volumes:
      - ${PWD}/50-server_mango.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf
      - mango_db:/var/lib/mysql

    network_mode: host

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma_mdb
    environment:
      PMA_HOSTS: 127.0.0.1,127.0.0.1
      PMA_PORTS: 6033,6034
      PMA_ARBITRARY: 1
    restart: always
    volumes:
      - ${PWD}/ports.conf:/etc/apache2/ports.conf

    network_mode: host
#
# fa di default il backup di sql (LNGS o LNF che sono il default)
#
  backupper_sql:
    restart: always
    image: gmazzitelli/backupper:v0.2
    container_name: backupper_sql
    environment:
       BCK_START_NAME: 'sql_${VM_SERVICE}'
    volumes:
       - /var/lib/docker/volumes/mariadb_mariadb/_data/:/root/data/
       - /tmp/:/tmp/

#
# solo per MANGO
#

  backupper_sql_mango:
    restart: always
    image: gmazzitelli/backupper:v0.2
    profiles: ["grafana"]
    container_name: backupper_sql_mango
    environment:
       BCK_START_NAME: 'sql_mango_${VM_SERVICE}'
    volumes:
       - /var/lib/docker/volumes/mariadb_mango_db/_data/:/root/data/
       - /tmp/:/tmp/

  tokener:
    image: gmazzitelli/tokener:v0.2
    container_name: tokener
    environment:
      REFRESH_TOKEN: ${REFRESH_TOKEN}
      IAM_CLIENT_SECRET: ${IAM_CLIENT_SECRET}
      IAM_CLIENT_ID: ${IAM_CLIENT_ID}
      IAM_TOKEN_ENDPOINT: ${IAM_TOKEN_ENDPOINT}
      SCOPES: ${SCOPES}

    volumes:
      - /tmp/:/tmp/

  tokener_tape:
    image: gmazzitelli/tokener:v0.2
    container_name: tokener_tape
    environment:
      REFRESH_TOKEN: ${TAPE_REFRESH_TOKEN}
      IAM_CLIENT_SECRET: ${TAPE_IAM_CLIENT_SECRET}
      IAM_CLIENT_ID: ${TAPE_IAM_CLIENT_ID}
      IAM_TOKEN_ENDPOINT: ${TAPE_IAM_TOKEN_ENDPOINT}
      SCOPES: ${TAPE_SCOPES}
      TOKEN_FILE: '/tmp/tape_token'
    volumes:
      - /tmp/:/tmp/

volumes:
  mariadb:
  mango_db:
