version: "3"

# services:
#   analyzer:
#     image: gmazzitelli/cygno-st:v2.0.1-cygno
#     container_name: analyzer
#     environment:
#       IAM_CLIENT_SECRET: ${IAM_CLIENT_SECRET}
#       IAM_CLIENT_ID: ${IAM_CLIENT_ID}
#       ENDPOINT_URL: ${ENDPOINT_URL}

#       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#       MYSQL_IP: ${MYSQL_IP}
#       MYSQL_USER: ${MYSQL_USER}
#       MYSQL_DATABASE: ${MYSQL_DATABASE}
#       MYSQL_PORT: ${MYSQL_PORT}
# # generic queue for test
#       HTC_IP: 131.154.99.182

#     volumes:
#       - ${PWD}/dev/init.sh:/root/init.sh
#       - ${PWD}/dev/.bashrc:/root/.bashrc
#       - ${PWD}/dev/:/root/dev/
#       - /tmp/:/tmp/
      
services:
  analyzer_ped:
    image: gmazzitelli/cygno-st:v2.0.1-cygno
    container_name: analyzer_ped
    environment:
      IAM_CLIENT_SECRET: ${IAM_CLIENT_SECRET}
      IAM_CLIENT_ID: ${IAM_CLIENT_ID}
      ENDPOINT_URL: ${ENDPOINT_URL}

      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_IP: ${MYSQL_IP}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PORT: ${MYSQL_PORT}
# generic queue for test
      HTC_IP: 131.154.99.182

    volumes:
      - ${PWD}/dev/init_ped.sh:/root/init.sh
      - ${PWD}/dev/.bashrc:/root/.bashrc
      - ${PWD}/dev/:/root/dev/
      - /tmp/:/tmp/


