
services:
  tape:
    image: gmazzitelli/cygno-tape:v1.0.7-cygno
    container_name: tape
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      BUCKET_TAG: 'LNGS'
      IAM_CLIENT_SECRET: ${IAM_CLIENT_SECRET}
      IAM_CLIENT_ID: ${IAM_CLIENT_ID}
      ENDPOINT_URL: ${ENDPOINT_URL}
      TAPE_TOKEN_FILE: '/tmp/tape_token'
      S3_TOKEN_FILE: '/tmp/token'

      MYSQL_IP: ${MYSQL_IP}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PORT: ${MYSQL_PORT}
    volumes:
      - $PWD/dev/:/root/dev
      - /tmp/:/tmp/
    depends_on:
      - tokener_s3
      - tokener_tape

  tape_mango:
    image: gmazzitelli/cygno-tape:v1.0.7-cygno
    container_name: tape_mango
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      BUCKET_TAG: 'MAN'
      BA_ACCESS_KEY_ID: ${BA_ACCESS_KEY_ID}
      BA_SECRET_ACCESS_KEY: ${BA_SECRET_ACCESS_KEY}
      ENDPOINT_URL: "https://swift.recas.ba.infn.it/"
      TAPE_TOKEN_FILE: '/tmp/tape_token'

      MYSQL_IP:  'tunnel_grafana34'
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: 'mango_db'
      MYSQL_PORT: 6034
    volumes:
      - ${PWD}/dev/:/root/dev
      - /tmp/:/tmp/
      - ${PWD}/dev/init_userpass.sh:/root/dev/init.sh
    depends_on:
      - tokener_s3
      - tokener_tape

  tape_lnf:
    image: gmazzitelli/cygno-tape:v1.0.7-cygno
    container_name: tape_lnf
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      BUCKET_TAG: 'LNF'
      BA_ACCESS_KEY_ID: ${BA_ACCESS_KEY_ID}
      BA_SECRET_ACCESS_KEY: ${BA_SECRET_ACCESS_KEY}
      ENDPOINT_URL: "https://swift.recas.ba.infn.it/"
      TAPE_TOKEN_FILE: '/tmp/tape_token'

      MYSQL_IP: 'tunnel_grafana33'
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: 'cygno_db'
      MYSQL_PORT: 6033
    volumes:
      - ${PWD}/dev/:/root/dev
      - /tmp/:/tmp/
      - ${PWD}/dev/init_userpass.sh:/root/dev/init.sh
    depends_on:
      - tokener_s3
      - tokener_tape

  tunnel:
    restart: always
    image: gmazzitelli/sshtunnel
    container_name: tunnel_grafana33
    environment:
       REMOTE_PORT: 6033
       REMOTE_APP_NAME: localhost
       LOCAL_PORT: 6033
       USER: mazzitel
       REMOTE_IP: grafana.cygno.cloud.infn.it
    volumes:
       - /root/.ssh/daq_id:/root/.ssh/id_rsa

  tunnel2:
    restart: always
    image: gmazzitelli/sshtunnel
    container_name: tunnel_grafana34
    environment:
       REMOTE_PORT: 6034
       REMOTE_APP_NAME: localhost
       LOCAL_PORT: 6034
       USER: mazzitel
       REMOTE_IP: grafana.cygno.cloud.infn.it
    volumes:
       - /root/.ssh/daq_id:/root/.ssh/id_rsa

# messo dentro analyzer dopo lo spegnimento dei tape
#  tokener_s3:
#    image: gmazzitelli/tokener:v0.2
#    container_name: tokener_s3
#    environment:
#      REFRESH_TOKEN: ${REFRESH_TOKEN}
#      IAM_CLIENT_SECRET: ${IAM_CLIENT_SECRET}
#      IAM_CLIENT_ID: ${IAM_CLIENT_ID}
#      IAM_TOKEN_ENDPOINT: ${IAM_TOKEN_ENDPOINT}
#      SCOPES: ${SCOPES}
#      TOKEN_FILE: '/tmp/token'
#
#    volumes:
#      - /tmp/:/tmp/

#  tokener_tape:
#    image: gmazzitelli/tokener:v0.2
#    container_name: tokener_tape
#    environment:
## RESPONSE="$(curl -s -u ${TAPE_IAM_CLIENT_ID}:${TAPE_IAM_CLIENT_SECRET} -d scopes="\"${TAPE_SCOPES}"\" -d grant_type=refresh_token -d refresh_token=${TAPE_REFRESH_TOKEN} ${TAPE_IAM_TOKEN_ENDPOINT})"
#      REFRESH_TOKEN: ${TAPE_REFRESH_TOKEN}
#      IAM_CLIENT_SECRET: ${TAPE_IAM_CLIENT_SECRET}
#      IAM_CLIENT_ID: ${TAPE_IAM_CLIENT_ID}
#      IAM_TOKEN_ENDPOINT: ${TAPE_IAM_TOKEN_ENDPOINT}
#      SCOPES: ${TAPE_SCOPES}
#      TOKEN_FILE: '/tmp/tape_token'
#
#    volumes:
#      - /tmp/:/tmp/
